### PR TITLE
Fix unaligned read.

### PR DESCRIPTION
**Pull request by Berrysoft**
Nightly will panic about it. I can reproduce the panic for `i686-pc-windows-msvc` target.

### CODE REVIEW

**Comment by repnop** [comment]
I think I see the root problem, those `.read_unaligned()`s you added are only covering up the actual issue which is here:

https://github.com/repnop/mac_address/blob/2635a51b4adf4d507249441aad1e7c89716f7a39/src/windows.rs#L96-L98

The `adapters_list` needs to be changed to use `Vec::with_capacity(<size> / size_of::<IP_ADAPTER_ADDRESSES_LH>())` (after asserting that the size is a multiple of that struct length) then have the length set on it. You can either modify your PR to make the appropriate change if you understand the explanation or I'll go ahead and push a fix after I get out of work today in about 5 hours. Thanks for reporting the issue! Though I'd ask that next time you find an issue, open it in the appropriate repo first so it can be discussed before putting out a PR to the RustSec DB so it can be assessed & addressed before putting out a notice for them, thanks :)

**Comment by repnop** [comment]
No worries! I'll write up a fix and get things sorted then :+1:

> Well, I'm still not sure that it is OK to assert all `IP_ADAPTER_ADDRESS` are the same size.

Hmm, I do see that the Win32 API docs say:

> `Length`: The length, in bytes, of this structure. Note that the length of the IP_ADAPTER_ADDRESSES structure changed on Windows XP with SP1 and later and also on Windows Vista and later.

So I'll get some feedback from people who are a bit more knowledgeable on this matter to make sure the fix is accurate, worst case I think I can just ensure the alignment and the fact that its a linked list sorts itself out since I don't care about most of the fields. Thanks for making me double check :+1:

**Comment by repnop** [comment]
If you're able to, I have what should be a fix up on the https://github.com/repnop/mac_address/tree/unaligned-read-fix-and-ci-stuff branch, are you able to use that instead of the crates.io depedency and see if its resolved for you? I'm quite confident it should be fixed but I was unable to reproduce the original panic on Linux compiling through mingw and running with `wine`, unfortunately, so I'd just like to have some kind of double-check here before publishing a new version.

**Comment by Berrysoft** [comment]
@repnop it is not solved. Tested with `i686-pc-windows-msvc`:

```
---- tests::convert stdout ----
thread 'tests::convert' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x90857c', src\windows.rs:78:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It seems that the winapi itself doesn't care about the alignment of the structures. Maybe wine treats the alignment better:)

**Comment by repnop** [comment]
okay I was finally able to reproduce the issue on my Windows VM, so I'm investigating what's up with it now. looks like the result of the `GetAdaptersAddresses` call is giving me a linked list that contains unaligned pointers:
```
ptr=0x016b4838
next=0x016b4d0c
```
hence the unaligned read when it goes to read the next MAC address. I'll let you know when I have a solution for this when I find out _why_ I'm getting an unaligned pointer back

**Comment by repnop** [comment]
Hi, sorry for the wait on the fix, I had some personal stuff come up. The issue seems to be the way that the 32-bit Windows ABI does struct alignment with >4 byte aligned types, causing the entire struct's alignment to not be promoted. I think this is honestly an LLVM/Rust issue since they both disagree on the alignment wrt the WinAPI, but I haven't opened an upstream issue about it, feel free to do so if you want. I've opted to only do the unaligned read for 32-bit targets as to not go crazy with stack usage on the 64-bit targets by reading the entire struct each time. I've tested the fix and it does seem to have fixed the problem and I'm publishing 1.1.5 here to get that fix out, so you should be good to go with that being released.

**Pull request closed without merging**
